name: Sync to Notion
on:
  push:
    branches: [main]
    paths:
      - './**'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync docs to Notion
        uses: Fencer-Security/nogisync@v1.2.0
        with:
          notion_api_key: ${{ secrets.NOTION_API_KEY }}
          notion_parent_page_id: ${{ secrets.NOTION_PARENT_PAGE_ID }}
          docs_path: '.'
